### ISSUE TITLE
Close fla files after convert to png

### ISSUE THREAD

**Issue by JeremyJones18** [jrrbru/flash-export#1]
This is a great script, but if i use it one a lot of fla files adobe flash professional closes because of not enough memory. When I run the batch script it opens each fla file in adobe flash professional but does not close the file after converting to png and just keeps opening more fla files. Is it possible to change the script to work as it does not but close the fla file before opening the next one?

**Comment by jrrbru** [comment]
Hi Jeremy,

Thanks for commenting. I've made a new branch at https://github.com/jrrbru/flash-export/tree/closeDocument that adds a call to `fl.closeDocument()` that I think will close the file. Please try it out and let me know if it fixes your issue.

**Comment by JeremyJones18** [comment]
I just tried it, and it worked perfectly! Thank you very much! I have another question if it would not be too much trouble. Is it possible to change the script to output .fxg instead of .png?

**Comment by jrrbru** [comment]
I'm glad it worked. I've merged the changes to the master branch at https://github.com/jrrbru/flash-export.

Unfortunately, I don't think that Flash offers the ability to export to .fxg from their scripting library. Sorry about that.
